### ISSUE TITLE
More issues with expired subkeys

### ISSUE THREAD

**Issue by maxtaco** [keybase/libkeybase-js#10]
See keybase/keybase-issues#1776

**Comment by oconnor663** [comment]
I worry this is going to be an issue with PGP key merging and non-expiring keys.

**Comment by maxtaco** [comment]
Any updates on this issue?

**Comment by oconnor663** [comment]
kourier's key (https://keybase.io/kourier) is supposed to be non-expiring. And indeed, when I import it by hand, that's what I see. But when the node client imports it, it comes out with a non-null expiration time. It turns out that the difference is the `time_travel` option. I don't yet know why. Any immediate theories @maxtaco?

Example code: https://gist.github.com/oconnor663/6ba322b1ad2a3fe8f257

**Comment by maxtaco** [comment]
let's go over it today

**Comment by maxtaco** [comment]
I addressed this in keybase/kbpgp#101.  In review now by @oconnor663

**Comment by maxtaco** [comment]
keybase/kbpgp#101 is merged and live.  Available in v2.0.47 of kbpgp.

**Comment by oconnor663** [comment]
node-client has been pushed
